[main]
import_ips = true 
import_prefixes = true
# import_cabling = "lldp"       # Valid options are ["lldp", "cdp", "config", false]
# import_intf_status = false     # If set as False, interface status will be ignore all together
#############################################################
#  IMPORTANT FOR VLAN IMPORT
#
# FOR IMPORT VLANS, PLEASE RUN CHECK MODE FIRST. If you get way too many VLANs on that, then the recommendation
# is to use "cli" as the import mode rather than config.
#
#############################################################
# import_vlans = "cli"         # Valid options are ["cli", "config", true, false]
excluded_platforms_cabling = ["cisco_asa"]

# Directory where the configurations can be find, organized in Batfish format
# configs_directory= "configs"

backend = "nautobot"            # Valid options are ["nautobot", "netbox"]

[inventory]
# Define a list of supported platform, 
# if defined all devices without platform or with a different platforms will be removed from the inventory
# supported_platforms = [ "cisco_ios", "cisco_nxos" ]

[inventory.settings]
# The information to connect to Nautobot needs to be provided, either in the config file or as environment variables
# These settings are specific to the Nautobot inventory, please check the documentation of your inventory for the 
# exist list of of available settings.
# For the address, include the scheme (http/https)
# address = ""                   # Alternative Env Variable : NAUTOBOT_ADDRESS
# token = ""  # Alternative Env Variable : NAUTOBOT_TOKEN
# verify_ssl = true                                   # Alternative Env Variable : NAUTOBOT_VERIFY_SSL

[network]
# To be able to pull live information from the devices, the credential information needs to be provided
# either in the configuration file or as environment variables ( & NETWORK_DEVICE_PWD)
# login = "username"      # Alternative Env Variable : NETWORK_DEVICE_LOGIN
# password = "password"   # Alternative Env Variable : NETWORK_DEVICE_PWD

[batfish]
#################################################################################
# Note: If using docker-compose right from repository use the environment var for
#       BATFISH_ADDRESS=batfish-test
# This will use the container name to connect to the host.
#################################################################################
# address= "localhost"    # Alternative Env Variable : BATFISH_ADDRESS
# api_key = "XXXX"      # Alternative Env Variable : BATFISH_API_KEY
# use_ssl = false

[logs]
# Define log level, currently the logs are printed on the screen
# level = "info" # "debug", "info", "warning"
