

[main]
import_ips = true
import_prefixes = true
import_cabling = "config"
import_vlans = "config"

nbr_workers = 5

backend = "netbox"

[inventory.settings]
filter="region=ni_multi_site_02"

[logs]
level = "debug"

